name: CI/CD Pipeline for Kubernetes Deployment

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-web-app:latest .

    - name: Save Docker image
      run: |
        docker save my-web-app:latest > my-web-app.tar

    - name: Upload Docker image
      uses: actions/upload-artifact@v3
      with:
        name: my-web-app
        path: my-web-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Docker image
      uses: actions/download-artifact@v3
      with:
        name: my-web-app

    - name: Load Docker image
      run: |
        docker load < my-web-app.tar

    - name: Deploy to Kubernetes
      run: |
        microk8s kubectl apply -f deployment.yaml
