name: CI/CD Pipeline for Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-web-app:latest .

    - name: Save Docker image locally
      run: |
        mkdir -p temp-docker-image
        docker save my-web-app:latest > temp-docker-image/my-web-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MicroK8s
      run: |
        sudo snap install microk8s --classic
        microk8s enable dns ingress

    - name: Load Docker image
      run: |
        docker load < temp-docker-image/my-web-app.tar

    - name: Deploy to Kubernetes
      run: |
        microk8s kubectl apply -f deployment.yaml

